### ISSUE TITLE
Searchbar needs implementation

### ISSUE THREAD

**Issue by chrispinkney** [TheATeam-566/Hermit#82]
We need to add functionality to the search bar located in the header component. Ideally this will get done after #78

**Comment by pyvelkov** [comment]
I will take this on.

**Comment by nilan01** [comment]
To implement the Searchbar on Hermitapp.me:

- [ ] fetch food items from firestore based on user input
- [ ] fetch for food items after 3 letters
  - [ ] after 3 letters have been typed, fetch for each 1 thenafter
- [ ] render cards based on search

**Comment by andregopichan** [comment]
Storyboard number 1 default homepage with no search query
Storyboard number 2 with more than three characters in search bar
Storyboard number 3 brings food component back to default layout

Reference below
 
![Searchbar](https://user-images.githubusercontent.com/61168001/106321321-1a16d680-6242-11eb-9352-67b27bef0fc5.PNG)

**Comment by pyvelkov** [comment]
Functionality is done. 

ToDo:

- [ ] Create a back-end api to fetch all items instead of running a loop to iterate through categories.
- [ ] Try to re-use FoodCard components instead of conditionally rendering SearchResults component.
- [ ] **(depending on if FoodCard can be re-used)** Add buttons to the cards inside SearchResults and make them functional.
- [ ] Move Search bar above categories
